version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER=$USER
        - GROUP=$GROUP
    container_name: mynginx
    ports:
      - "8080:80"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always